# --- !Ups

CREATE TABLE TB_USER (
  ID INTEGER NOT NULL AUTO_INCREMENT, 
  EMAIL VARCHAR(50), 
  PASSWORD VARCHAR(12),
  ADMIN BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
); 


CREATE TABLE TB_MOVIE (
  ID INTEGER NOT NULL AUTO_INCREMENT, 
  TITLE VARCHAR(50), 
  DIRECTOR VARCHAR(50),
  PRODUCTION_YEAR INTEGER(4),
  PRIMARY KEY (ID)
); 

# --- !Downs

DROP TABLE TB_USER;
DROP TABLE TB_MOVIE;
